server:
  port: 18881

spring:
  application:
    name: service-dataetler
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.154:8848
        namespace: dev
  datasource:
    url: jdbc:mysql://dyh-test-db.rwlb.rds.aliyuncs.com:3306/data_mart
    username: data_mart
    password: ODM1MmUyYjhjNmY
    driver-class-name: com.mysql.cj.jdbc.Driver
